modLoader="javafml" 
loaderVersion="[40,)" 
license="MIT License"
[[mods]] 
modId="blue_hearts" 
version="beta" 
displayName="Blue Hearts" 
displayURL="https://github.com/antth-Luca/ModBlueHearts" 
logoFile=""
credits="Inspired by Hollow Knight's \"Lifeblood\"" 
authors="antthLuca" 
description='''
Life and Absorption? Go further!

Blue hearts that are restored by sleep...
'''

[[dependencies.blue_hearts]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blue_hearts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"