modLoader="javafml" 
loaderVersion="[45,)" 
license="Custom license (on GitHub repository)"
[[mods]] 
modId="blue_hearts" 
version="2.1" 
displayName="Blue Hearts" 
displayURL="https://github.com/antth-Luca/ModBlueHearts" 
logoFile="logo.png"
credits="Inspired by Hollow Knight's \"Lifeblood\"" 
authors="antthLuca" 
description='''
Life and Absorption? Go further!

Blue hearts that are restored by sleep...
'''

[[dependencies.blue_hearts]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blue_hearts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
